### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by KenCope** [jalim/SimpleBoilLogic#2]
How do you install this?  Thanks

**Comment by jalim** [comment]
Hi Ken, sorry for the delay in responding.  Did you work how to install?  It should be as simple as clicking install from the plugins/addons page within the Craftbeerpi interface, then choose it as your logic for the kettle.

**Comment by KenCope** [comment]
For some reason when I install those admins, I cannot get back into CBPi. It gives me an unable to open error.

**Comment by KenCope** [comment]
I mean install the add ons

**Comment by jalim** [comment]
Make sure you are using the Master branch (version) of CBPI, there are bugs if you "Activate" Version 3.0 or Version 3.1 on the system page.

**Comment by KenCope** [comment]
I apologize, but I’m not following.

I had 2.2 installed, but couldn’t figure out how to get plugins added in, so I went to 3.0.

________________________________

**Comment by jalim** [comment]
2.2 Doesn't have plugins at all.  The new CBPI3 does but as it is still in development there are versions of it that don't work properly.  If you follow the instructions here: https://github.com/Manuel83/craftbeerpi3
you should be able to install plugins.

The problem arrises when you go to the System page and click Activate on either the 3.0 or 3.1 releases.  For what ever reason these versions are not working with plugins and you must use the "Master" version.

**Comment by KenCope** [comment]
I will check it out. Thanks so much for your help!

________________________________

**Comment by jalim** [comment]
No worries, unfortunately the whole system is still not quite at a stage where it is battle hardened and ready for the general public, it still requires a lot of patience and a degree of technical know how.
